version: "3.9"
services:
  chat:
    build: .
    ports:
      - "8080:8080"
  rabbitmq:
    image: "rabbitmq:3.9-management"
    hostname: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
  webapp:
    build: ./webapp
    ports:
      - "3000:3000"
    command: npm start
